# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-11 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_books_in_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='in_print',
        ),
        migrations.RemoveField(
            model_name='books',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
